import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('C:\\Users\\HP\\dataScience lab\\iris.csv')
print("First few rows of the dataset:")
print(df.head())
print("\nDescriptive Statistics:")
print(df.describe())n
print("\nMean of each Column:")
print(df.select_dtypes(include='number').mean())
print("\nMedian of each Column:")
print(df.select_dtypes(include='number').median())
print("\nStandard Deviation for each Column:")
print(df.select_dtypes(include='number').std())
print("\nCount of unique values for each column:")
print(df.nunique())
print("\nClass distribution:")
print(df['class'].value_counts())
print("\nCorrelation Matrix:")
print(df.select_dtypes(include='number').corr())
print("\nGroup by 'class' and calculate the mean:")
print(df.groupby('class').mean())
plt.figure(figsize=(10,6))
df.drop('class', axis=1).boxplot() 
plt.title("Boxplot of Numerical Features")
plt.show()
